In [12]:
import pandas as pd

faq = pd.read_csv("../FAQ_dataset/customer_support_500_cleaned.csv")

faq.head()

                      question            answer   category
0  Sample customer question 1?  Sample answer 1.  Category2
1  Sample customer question 2?  Sample answer 2.  Category3
2  Sample customer question 3?  Sample answer 3.  Category4
3  Sample customer question 4?  Sample answer 4.  Category5
4  Sample customer question 5?  Sample answer 5.  Category1

In [13]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   question  500 non-null    object
 1   answer    500 non-null    object
 2   category  500 non-null    object
dtypes: object(3)
memory usage: 11.8+ KB

In [14]:
products["category"].value_counts()

category
Category2    100
Category3    100
Category4    100
Category5    100
Category1    100
Name: count, dtype: int64

In [16]:
products.columns

Index(['question', 'answer', 'category'], dtype='object')

Products

In [18]:
import pandas as pd

products = pd.read_csv("../ecommerce_dataset/products.csv")

In [19]:
products.columns

Index(['product_id', 'product_name', 'category', 'brand', 'price', 'rating'], dtype='object')

In [20]:
products["category"].value_counts()

category
Clothing          213
Toys              213
Pet Supplies      212
Beauty            207
Electronics       203
Home & Kitchen    199
Books             194
Automotive        193
Groceries         183
Sports            183
Name: count, dtype: int64

In [21]:
products["brand"].value_counts().head(20)

brand
Zenith       190
Harbor       183
Nimbus       182
GreenLeaf    174
Astra        165
Willow       165
NeoTech      163
Orion        163
Everest      157
Solace       156
Acme         155
Pulse        147
Name: count, dtype: int64

In [29]:
def search_products(
    category=None,
    min_price=None,
    max_price=None,
    min_rating=None
):
    result = products.copy()

    if category:
        result = result[
            result["category"].str.contains(category, case=False, na=False)
        ]

    if min_price is not None:
        result = result[result["price"] >= min_price]

    if max_price is not None:
        result = result[result["price"] <= max_price]

    if min_rating is not None:
        result = result[result["rating"] >= min_rating]

    if "rating" in result.columns:
        result = result.sort_values(
        by="rating",
        ascending=False
    )

    return result

In [30]:
search_products(
    category="Electronics",
    max_price=200,
    min_rating=4
)

     product_id   product_name     category    brand   price  rating
1531    P001532  NeoTech Admit  Electronics  NeoTech  137.82    4.65

In [31]:
def best_products(category=None, top_n=5):

    result = products.copy()

    if category:
        result = result[
            result["category"].str.contains(category, case=False, na=False)
        ]

    result = result.sort_values(
        by="rating",
        ascending=False
    )

    return result.head(top_n)

In [32]:
best_products("Electronics")

     product_id         product_name     category      brand    price  rating
191     P000192           Pulse Near  Electronics      Pulse   455.43    4.88
1035    P001036       Pulse Security  Electronics      Pulse  1075.65    4.86
1652    P001653       Nimbus Control  Electronics     Nimbus  1187.64    4.85
748     P000749  GreenLeaf Authority  Electronics  GreenLeaf   254.08    4.83
457     P000458        Everest Black  Electronics    Everest   982.10    4.82

In [33]:
def compare_products(product1, product2):

    p1 = products[
        products["product_name"].str.lower() == product1.lower()
    ]

    p2 = products[
        products["product_name"].str.lower() == product2.lower()
    ]

    if p1.empty:
        return f"'{product1}' not found."

    if p2.empty:
        return f"'{product2}' not found."

    comparison = pd.DataFrame({
        "Feature": ["Price", "Rating", "Category", "Brand"],
        product1: [
            p1.iloc[0]["price"],
            p1.iloc[0]["rating"],
            p1.iloc[0]["category"],
            p1.iloc[0]["brand"],
        ],
        product2: [
            p2.iloc[0]["price"],
            p2.iloc[0]["rating"],
            p2.iloc[0]["category"],
            p2.iloc[0]["brand"],
        ]
    })

    return comparison

In [34]:
compare_products(
    "NeoTech Help",
    "Astra Upon"
)

    Feature    NeoTech Help Astra Upon
0     Price           12.72      20.58
1    Rating             4.6       2.83
2  Category  Home & Kitchen       Toys
3     Brand         NeoTech      Astra

In [51]:
def recommend_products(
    category=None,
    max_price=None,
    min_rating=None,
    top_n=5
):
    result = products.copy()

    # Filter by category
    if category:
        result = result[
            result["category"].str.contains(category, case=False, na=False)
        ]

    # Filter by price
    if max_price is not None:
        result = result[result["price"] <= max_price]

    # Filter by rating
    if min_rating is not None:
        result = result[result["rating"] >= min_rating]

    result["score"] = (
    result["rating"] * 0.8 +
    (1 / result["price"]) * 100 * 0.2
    )

    result = result.sort_values(
    by="score",
    ascending=False
    )

    return result[
    [
        "product_name",
        "category",
        "brand",
        "price",
        "rating"
    ]
].head(top_n)

In [52]:
recommend_products(
    category="Electronics",
    max_price=300,
    min_rating=4
)

             product_name     category      brand   price  rating
748   GreenLeaf Authority  Electronics  GreenLeaf  254.08    4.83
1531        NeoTech Admit  Electronics    NeoTech  137.82    4.65
722            Astra Move  Electronics      Astra  244.36    4.59
715           Acme Factor  Electronics       Acme  273.91    4.48
1068          Nimbus Cost  Electronics     Nimbus  250.79    4.19

In [48]:
products.columns

Index(['product_id', 'product_name', 'category', 'brand', 'price', 'rating'], dtype='object')

In [53]:
def get_product(product_name):

    result = products[
        products["product_name"].str.contains(
            product_name,
            case=False,
            na=False
        )
    ]

    return result

In [54]:
get_product("NeoTech")

     product_id      product_name        category    brand    price  rating
1       P000002   NeoTech Someone       Groceries  NeoTech    21.46    3.87
5       P000006      NeoTech When            Toys  NeoTech    18.61    3.20
38      P000039         NeoTech A        Clothing  NeoTech    33.41    4.75
41      P000042     NeoTech Power            Toys  NeoTech    36.95    4.49
43      P000044  NeoTech Possible            Toys  NeoTech    53.51    2.70
...         ...               ...             ...      ...      ...     ...
1933    P001934      NeoTech Song      Automotive  NeoTech   286.31    4.73
1934    P001935     NeoTech Watch           Books  NeoTech    77.28    3.83
1960    P001961     NeoTech Write     Electronics  NeoTech  1038.94    3.18
1978    P001979       NeoTech Our     Electronics  NeoTech   662.22    2.76
1995    P001996      NeoTech Turn  Home & Kitchen  NeoTech    69.46    4.28

[163 rows x 6 columns]

In [55]:
def compare_summary(product1, product2):

    p1 = get_product(product1).iloc[0]
    p2 = get_product(product2).iloc[0]

    summary = []

    if p1["rating"] > p2["rating"]:
        summary.append(
            f"{p1['product_name']} has a higher rating."
        )
    else:
        summary.append(
            f"{p2['product_name']} has a higher rating."
        )

    if p1["price"] < p2["price"]:
        summary.append(
            f"{p1['product_name']} is cheaper."
        )
    else:
        summary.append(
            f"{p2['product_name']} is cheaper."
        )

    if p1["brand"] == p2["brand"]:
        summary.append("Both products are from the same brand.")

    if p1["category"] == p2["category"]:
        summary.append("Both belong to the same category.")

    return summary

In [56]:
compare_summary(
    "NeoTech",
    "Harbor"
)

['Harbor Go has a higher rating.', 'NeoTech Someone is cheaper.']