In [5]:
import pandas as pd

products = pd.read_csv("../ecommerce_dataset/products.csv")
customers = pd.read_csv("../ecommerce_dataset/users.csv")
orders = pd.read_csv("../ecommerce_dataset/orders.csv")
order_items = pd.read_csv("../ecommerce_dataset/order_items.csv")
reviews = pd.read_csv("../ecommerce_dataset/reviews.csv")
events = pd.read_csv("../ecommerce_dataset/events.csv")

In [6]:
products.head()

  product_id     product_name        category    brand   price  rating
0    P000001         Astra Be        Clothing    Astra  157.89    4.08
1    P000002  NeoTech Someone       Groceries  NeoTech   21.46    3.87
2    P000003     Acme Discuss          Sports     Acme  265.37    3.46
3    P000004     Nimbus South     Electronics   Nimbus  541.41    4.14
4    P000005    Astra Capital  Home & Kitchen    Astra  198.00    3.97

In [7]:
def explore(df, name):
    print("=" * 60)
    print(name)
    print("=" * 60)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nInfo:")
    print(df.info())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicates:")
    print(df.duplicated().sum())

    print("\nFirst Rows:")
    display(df.head())

In [12]:
explore(products, "Products")
explore(customers, "Customers")
explore(orders, "Orders")
explore(order_items, "Order Items")
explore(reviews, "Reviews")
explore(events, "Events")

============================================================
Products
============================================================

Shape:
(2000, 6)

Columns:
['product_id', 'product_name', 'category', 'brand', 'price', 'rating']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    2000 non-null   object
 1   product_name  2000 non-null   object
 2   category      2000 non-null   object
 3   brand         2000 non-null   object
 4   price         2000 non-null   float64
 5   rating        2000 non-null   float64
dtypes: float64(2), object(4)
memory usage: 93.9+ KB
None

Missing Values:
product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
dtype: int64

Duplicates:
0

First Rows:

  product_id     product_name        category    brand   price  rating
0    P000001         Astra Be        Clothing    Astra  157.89    4.08
1    P000002  NeoTech Someone       Groceries  NeoTech   21.46    3.87
2    P000003     Acme Discuss          Sports     Acme  265.37    3.46
3    P000004     Nimbus South     Electronics   Nimbus  541.41    4.14
4    P000005    Astra Capital  Home & Kitchen    Astra  198.00    3.97

============================================================
Customers
============================================================

Shape:
(10000, 6)

Columns:
['user_id', 'name', 'email', 'gender', 'city', 'signup_date']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      10000 non-null  object
 1   name         10000 non-null  object
 2   email        10000 non-null  object
 3   gender       10000 non-null  object
 4   city         10000 non-null  object
 5   signup_date  10000 non-null  object
dtypes: object(6)
memory usage: 468.9+ KB
None

Missing Values:
user_id        0
name           0
email          0
gender         0
city           0
signup_date    0
dtype: int64

Duplicates:
0

First Rows:

,user_id,name,email,gender,city,signup_date
0,U000001,Angel Hill,donaldgarcia@example.net,Other,New Roberttown,2025-03-13
1,U000002,Jesse Guzman,jennifermiles@example.com,Male,South Bridget,2024-03-05
2,U000003,Adam Shaffer,jpeterson@example.org,Male,Curtisfurt,2025-07-07
3,U000004,Melanie Munoz,blairamanda@example.com,Other,New Kellystad,2024-03-07
4,U000005,Janet Williams,kendragalloway@example.org,Female,South Joshuastad,2025-01-29

============================================================
Orders
============================================================

Shape:
(20000, 5)

Columns:
['order_id', 'user_id', 'order_date', 'order_status', 'total_amount']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      20000 non-null  object
 1   user_id       20000 non-null  object
 2   order_date    20000 non-null  object
 3   order_status  20000 non-null  object
 4   total_amount  20000 non-null  float64
dtypes: float64(1), object(4)
memory usage: 781.4+ KB
None

Missing Values:
order_id        0
user_id         0
order_date      0
order_status    0
total_amount    0
dtype: int64

Duplicates:
0

First Rows:

    order_id  user_id                  order_date order_status  total_amount
0  O00000001  U009310  2025-09-09T14:52:37.292731   processing        689.66
1  O00000002  U003247  2025-04-15T01:18:27.193404    completed       1666.85
2  O00000003  U007252  2025-04-27T15:37:48.008624   processing        665.06
3  O00000004  U008986  2025-10-04T20:35:22.204857    cancelled        689.50
4  O00000005  U008537  2024-11-13T08:15:18.498252    cancelled        860.50

============================================================
Order Items
============================================================

Shape:
(43525, 7)

Columns:
['order_item_id', 'order_id', 'product_id', 'user_id', 'quantity', 'item_price', 'item_total']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43525 entries, 0 to 43524
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  43525 non-null  object
 1   order_id       43525 non-null  object
 2   product_id     43525 non-null  object
 3   user_id        43525 non-null  object
 4   quantity       43525 non-null  int64
 5   item_price     43525 non-null  float64
 6   item_total     43525 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.3+ MB
None

Missing Values:
order_item_id    0
order_id         0
product_id       0
user_id          0
quantity         0
item_price       0
item_total       0
dtype: int64

Duplicates:
0

First Rows:

,order_item_id,order_id,product_id,user_id,quantity,item_price,item_total
0,I00000001,O00000001,P001758,U009310,2,8.07,16.14
1,I00000002,O00000001,P001119,U009310,1,74.08,74.08
2,I00000003,O00000001,P001794,U009310,1,576.97,576.97
3,I00000004,O00000001,P001038,U009310,1,22.47,22.47
4,I00000005,O00000002,P000859,U003247,1,422.22,422.22

============================================================
Reviews
============================================================

Shape:
(15000, 7)

Columns:
['review_id', 'order_id', 'product_id', 'user_id', 'rating', 'review_text', 'review_date']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    15000 non-null  object
 1   order_id     15000 non-null  object
 2   product_id   15000 non-null  object
 3   user_id      15000 non-null  object
 4   rating       15000 non-null  int64
 5   review_text  15000 non-null  object
 6   review_date  15000 non-null  object
dtypes: int64(1), object(6)
memory usage: 820.4+ KB
None

Missing Values:
review_id      0
order_id       0
product_id     0
user_id        0
rating         0
review_text    0
review_date    0
dtype: int64

Duplicates:
0

First Rows:

,review_id,order_id,product_id,user_id,rating,review_text,review_date
0,R00000528,O00000237,P001326,U001094,2,Color was different from images.,2025-10-14T12:03:56.749446
1,R00005792,O00002627,P000329,U001858,4,Highly recommend this brand.,2024-10-09T08:04:50.171793
2,R00036604,O00016798,P001160,U008109,4,Highly recommend this brand.,2024-06-03T05:11:16.787214
3,R00040163,O00018414,P001427,U006835,5,Highly recommend this brand.,2024-02-12T06:41:50.215810
4,R00031127,O00014300,P001639,U007148,3,Item arrived damaged.,2025-01-20T05:32:09.398860

============================================================
Events
============================================================

Shape:
(80000, 5)

Columns:
['event_id', 'user_id', 'product_id', 'event_type', 'event_timestamp']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         80000 non-null  object
 1   user_id          80000 non-null  object
 2   product_id       80000 non-null  object
 3   event_type       80000 non-null  object
 4   event_timestamp  80000 non-null  object
dtypes: object(5)
memory usage: 3.1+ MB
None

Missing Values:
event_id           0
user_id            0
product_id         0
event_type         0
event_timestamp    0
dtype: int64

Duplicates:
0

First Rows:

    event_id  user_id product_id event_type             event_timestamp
0  E00000001  U009798    P001393       cart  2025-07-08T14:28:55.893919
1  E00000002  U005881    P000669       view  2025-10-19T23:00:44.067982
2  E00000003  U006348    P001404       view  2025-05-09T07:02:42.256662
3  E00000004  U002664    P000400       cart  2025-07-19T22:47:07.019634
4  E00000005  U005776    P000392       view  2024-10-24T10:20:33.602165